DROP TABLE public."MassShootingData";

CREATE TABLE public."MassShootingData"
(
	Case_No	integer,
	Shooter_Last_Name	character varying,
	Shooter_First_Name	character varying,
	Full_Date	date,
	Day_of_Week	character varying,
	Day	integer,
	Month	integer,
	Year	integer,
	Shooting_Location_Address	character varying,
	Zip_Code	character varying,
	Latitude	numeric,
	Longitude	numeric,
	City	character varying,
	State	character varying,
	Region	integer,
	UrbanSuburbanRural	character varying,
	Location	character varying,
	Bifurcated	character varying,
	If_Bifurcated_Other_Location	character varying,
	Armed_person_on_scene	character varying,
	Number_killed	integer,
	Number_injured	integer,
	Victims_known_or_unknown	character varying,
	Specify_known_victims	character varying,
	Kidnapping_hostage_situation	character varying,
	Age	integer,
	Gender	character varying,
	Race	character varying,
	Immigrant	character varying,
	Sexual_orientation	character varying,
	Religion	character varying,
	Education	character varying,
	Relationship_Status	character varying,
	Children	character varying,
	Employment_status	character varying,
	Employment_Type	character varying,
	Military_Service	character varying,
	Miltary_Branch	character varying,
	Criminal_Record_Police_Contact	integer,
	Previous_homicides	integer,
	History_of_Violence	integer,
	Interest_in_Firearms	integer,
	Gang_Affiliation	integer,
	Terrorist_Affiliation	integer,
	Bully	integer,
	Bullied	integer,
	Grew_up_with_single_parent	integer,
	Parental_suicide	integer,
	Childhood_trauma	integer,
	Adult_trauma	integer,
	Recent_break_up	integer,
	Employment_change_or_trouble	integer,
	Signs_of_a_crisis	integer,
	Suicidality	integer,
	Prior_Hospitalization	integer,
	Prior_Counseling	integer,
	Psychiatric_Medication	integer,
	Mental_Illness	integer,
	Autism_Spectrum	integer,
	Substance_Use	integer,
	Health_issues	integer,
	Health_Specify	character varying,
	Racial_element	integer,
	Racism_Xenophobia	integer,
	Religious_Hate	integer,
	Notable_misogyny	integer,
	Homophobia	integer,
	Employment_Issue	integer,
	Economic_Issue	integer,
	Legal_Issue	integer,
	Domestic_spillage	integer,
	Relationship_Issue	integer,
	Interpersonal_Conflict	integer,
	Psychosis	integer,
	Fame_seeking	integer,
	Other	integer,
	Unknown1	integer,
	Social_Media_Use	integer,
	Leakage	integer,
	Interest_in_past_mass_violence	integer,
	Relationship_with_another_shooting	integer,
	Specify_relationship_to_other_shootings	character varying,
	Legacy_token	integer,
	Planning	integer,
	Performance	integer,
	Total_weapons_brought_to_the_scene	integer,
	N_Handguns	integer,
	N_Shotguns	integer,
	N_Rifles	integer,
	N_Assault_Rifles	integer,
	N_Submachine_Guns	integer,
	Legal_Purchase	integer,
	Illegal_Purchase	integer,
	Assembled_with_Legal_Parts	integer,
	Gifted	integer,
	Theft	integer,
	Unknown2	integer,
	Other_weapons_or_gear	integer,
	Specify_other_weapons_and_gear	character varying,
	On_Scene_Outcome	integer,
	Attempt_to_Flee	integer,
	Insanity_Defense	integer,
	Criminal_Sentence	integer
);


